### ISSUE TITLE
petition for silly command

### ISSUE THREAD

**Issue by p-i-c-o** [CatGuyMoment/silly-utils#4]
this command will send a random silly thingy. for example, it could choose a random sentence of the following!

```The flying spaghetti monster served lasagna at the intergalactic picnic.
The purple elephant danced the tango with a talking watermelon.
The cow jumped over the moon and landed on a stack of pancakes.
The pineapple and the pineapple upside-down cake had a heated debate about their existence.
The socks in my drawer formed a secret society and planned a rebellion against the laundry machine.
The teapot grew legs and ran off to join a circus as a high-wire walker.
The clouds conspired to rain cats and dogs, but ended up with a shower of rubber ducks instead.
The banana went on strike, demanding to be called a "curvy fruit" instead of a "yellow bendy thing."
The snoring tree kept the entire forest awake with its loud nocturnal symphony.
The toothpaste squeezed itself onto the toothbrush, insisting on taking over the daily brushing routine.
```

suggested by p-i-c-o
<img src="https://github.com/CatGuyMoment/silly-utils/assets/95228665/612f1803-bcd4-43bf-ac13-033c3b781d7e" width=100>

**Comment by CatGuyMoment** [comment]
There is already something really similar but different to this being worked on, where you are capable of sending messages and commands directly from config.json, the most recent message from the selected channel, or a pre-selected function (eg. random). Combined with GPT-3, these actions can be combined to make essentially any kind of modular or randomly selected message/command you want.

Not in any of the branches yet since it's still really buggy and exploitable.

**Comment by CatGuyMoment** [comment]
The concept for this plugin is basically "how can I simplify and softcode talking to people"

**Comment by p-i-c-o** [comment]
Interesting, thank you for elaborating.
